optimized rtc_git and rtc_tgz support

diff --git a/config/includes.chroot/usr/local/bin/rtc_git b/config/includes.chroot/usr/local/bin/rtc_git
--- a/config/includes.chroot/usr/local/bin/rtc_git
+++ b/config/includes.chroot/usr/local/bin/rtc_git
@@ -1,48 +1,55 @@
 #!/bin/sh
 
+ME="${0##*/}"
+
+echo ${ME}
+
 . /etc/environment
+. /usr/local/bin/rtc_fallback
 
 gitpath=""
 
-GitLoad () {
-	echo "try to load rtc repo: ${xgiturl} ${gitpath}"
-	eval cd /tmp && git clone --depth=1 -b "${gitpath}" --single-branch "${xgiturl}" && cp -a "${xgitreponame}"/fs_overlay/* / && rm -r "${xgitreponame}"
-	# unfortunately github does not support remote archive, hrz gitolite does:
-	# eval cd / && git archive --format=tar --remote="${giturl}" | tar xf - --strip-components=1
+GitLoad() {
+        echo "try to load rtc repo: ${xgiturl} ${gitpath}"
+        eval cd /tmp && git clone --depth=1 -b "${gitpath}" --single-branch "${xgiturl}" && cp -a "${xgitreponame}"/fs_overlay/* / && rm -r "${xgitreponame}"
+	if [ $? -eq 0 ] ; then
+		echo "GitLoad ok"
+	else 
+		exit $1
+	fi
 }
 
-if [ -z "${xgiturl}" ] || [ -z "${xgitreponame}" ] 
+trap 'Fallback' EXIT
+
+if [ -z "${xgiturl}" ] || [ -z "${xgitreponame}" ]
 then
-	echo "giturl or gitreponame needed, abort!"
-	return 0
+        echo "xgiturl and xgitreponame in kernel params needed, abort!"
+        exit 1
 fi
 
 echo "add ssh key for agent..."
 . /usr/local/bin/start_ssh
-	
-if [ ! -z "${xgitbranch}" ] ; then
-	#repo=""
-	repo=$(/usr/bin/git ls-remote "${xgiturl}" "${xgitbranch}")
-	if [ -z "${repo}" ]
-	then
-		echo "no git branch found: ${xgiturl} ${xgitbranch}"
-	else
-		echo "git branch found: ${repo}"
-		gitpath="${xgitbranch}"
-		GitLoad
-	fi
+
+repo=$(/usr/bin/git ls-remote "${xgiturl}" "${xrtcbranch}")
+if [ -z "${repo}" ] ; then
+	echo "no git branch found: ${xgiturl} ${xrtcbranch}"
+	exit 1
+else
+	echo "git branch found: ${repo}"
+	gitpath="${xrtcbranch}"
+	GitLoad
 fi
 
-if [ "${xgithost}" = "1" ] ; then
-	#repo=""
-	repo=$(/usr/bin/git ls-remote "${xgiturl}" "${host}")
-	if [ -z "${repo}" ] ; then
-		echo "no host repo found: ${xgiturl} ${host}"
-	else
-		gitpath="${host}"
-		echo "host repo found: ${repo}"
-		GitLoad
-	fi
+# override branch with xrtchost
+if [ "${xrtchost}" = "1" ] ; then
+        #repo=""
+        repo=$(/usr/bin/git ls-remote "${xgiturl}" "${host}")
+        if [ -z "${repo}" ] ; then
+                echo "no host repo found: ${xgiturl} ${host}"
+		exit 1
+        else
+                gitpath="${host}"
+                echo "host repo found: ${repo}"
+                GitLoad
+        fi
 fi
-
-
diff --git a/config/includes.chroot/usr/local/bin/rtc_tgz b/config/includes.chroot/usr/local/bin/rtc_tgz
--- a/config/includes.chroot/usr/local/bin/rtc_tgz
+++ b/config/includes.chroot/usr/local/bin/rtc_tgz
@@ -1,27 +1,41 @@
 #!/bin/sh
 
+ME="${0##*/}"
+
+echo ${ME}
+
 . /etc/environment
+. /usr/local/bin/rtc_fallback
 
-echo "exec rtc-tgz"
+url=""
 
-if [ -z "${xtgzurl}" ] ; then
-	echo "tgzurl needed, aborted!"
-	exit 1
+TgzLoad() {
+	echo "try to load tgz repo: ${url}"
+	eval cd /tmp && wget --user-agent="${xrtcagent}" --no-check-certificate -qO- ${url} | tar xz && cp -r fs_overlay/* / && rm -r fs_overlay
+	if [ $? = 0 ] ; then
+		echo "TgzLoad ok"
+	else
+		exit $1
+	fi
+}
+
+trap 'Fallback' EXIT
+
+if [ -z "${xtgzurl}" ] || [ -z "${xrtcagent}" ]
+then
+	echo "xtgzurl and xrtcagent in kernel params needed, abort!"
+        exit 1
 fi
 
-if [ -z "${xrtcagent}" ] ; then
-	echo "xrtcagent needed, aborted!"
-	exit 1
+if [ "${xhost}" = "1" ] ; then
+	url="${xtgzurl}/${host}.tgz"
 fi
 
-if [ "${xtgzhost}" = "1" ] ; then
-	tgzurl="${xtgzurl}/${host}.tgz"
+url="${xtgzurl}/${xrtcbranch}/fs_overlay.tgz"
+
+TgzLoad
+
+if [ "${xrtchost}" = "1" ] ; then
+	url="${xtgzurl}/${host}/fs_overlay.tgz"
+	TgzLoad
 fi
-
-echo "try to load rtc tgz file: ${xtgzurl}"
-cd /tmp && wget --user-agent="${xrtcagent}" --no-check-certificate -qO- $xtgzurl | tar xz && cp -r fs_overlay/* / && rm -r fs_overlay
-
-echo "rtc-tgz done"
-exit $?
-
-
